components:
    schemas:
        Facet:
            properties:
                aggregationName:
                    type: string
                attributes:
                    additionalProperties:
                        type: object
                    type: object
                frequencyThreshold:
                    type: integer
                maxTerms:
                    type: integer
                name:
                    type: string
                values:
                    items:
                        type: object
                    type: array
            type: object
        SearchRequestBody:
            properties:
                facets:
                    items:
                        $ref: "#/components/schemas/Facet"
                    type: array
                searchContextAttributes:
                    additionalProperties:
                        type: object
                    type: object
            type: object
        SearchResponse:
            properties:
                aggregationResults:
                    additionalProperties:
                        type: object
                    type: object
                documents:
                    items:
                        type: object
                    type: array
                facets:
                    additionalProperties:
                        type: object
                    type: object
                maxScore:
                    format: float
                    type: number
                page:
                    type: integer
                pageSize:
                    type: integer
                request:
                    type: object
                response:
                    type: object
                totalHits:
                    format: int64
                    type: integer
            type: object
        Suggestion:
            properties:
                attributes:
                    type: object
                score:
                    format: float
                    type: number
                text:
                    type: string
            type: object
        SuggestionsContributorConfiguration:
            properties:
                attributes:
                    type: object
                contributorName:
                    type: string
                displayGroupName:
                    type: string
                size:
                    type: integer
            type: object
        SuggestionsContributorResults:
            properties:
                attributes:
                    type: object
                displayGroupName:
                    type: string
                suggestions:
                    items:
                        $ref: "#/components/schemas/Suggestion"
                    type: array
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.portal.search.rest.client', and version '1.0.9'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/search":
        post:
            description:
                "Search the company index for matching content. Using this endpoint requires a dev feature flag: set feature.flag.LPS-179669 to true."
            operationId: postSearch
            parameters:
                - in: query
                  name: basicFacetSelection
                  schema:
                      type: boolean
                - in: query
                  name: entryClassNames
                  schema:
                      items:
                          type: string
                      type: array
                - in: query
                  name: explain
                  schema:
                      type: boolean
                - in: query
                  name: groupIds
                  schema:
                      items:
                          format: int64
                          type: integer
                      type: array
                - in: query
                  name: includeAssetSearchSummary
                  schema:
                      type: boolean
                - in: query
                  name: includeAssetTitle
                  schema:
                      type: boolean
                - in: query
                  name: includeRequest
                  schema:
                      type: boolean
                - in: query
                  name: includeResponse
                  schema:
                      type: boolean
                - in: query
                  name: keywords
                  schema:
                      type: string
                - in: query
                  name: resultFields
                  schema:
                      items:
                          type: string
                      type: array
                - in: query
                  name: scopeGroupId
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SearchRequestBody"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SearchRequestBody"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SearchResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SearchResponse"
            tags: ["SearchResponse"]
    /suggestions:
        post:
            operationId: postSuggestionsPage
            parameters:
                - in: query
                  name: currentURL
                  schema:
                      type: string
                - in: query
                  name: destinationFriendlyURL
                  schema:
                      type: string
                - in: query
                  name: groupId
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: keywordsParameterName
                  schema:
                      type: string
                - in: query
                  name: plid
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: scope
                  schema:
                      type: string
                - in: query
                  name: search
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            items:
                                $ref: "#/components/schemas/SuggestionsContributorConfiguration"
                            type: array
                    application/xml:
                        schema:
                            items:
                                $ref: "#/components/schemas/SuggestionsContributorConfiguration"
                            type: array
                required: false
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SuggestionsContributorResults"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SuggestionsContributorResults"
                                type: array
            tags: ["Suggestion"]